### ISSUE TITLE
The Job "copy-certs-172.17.4.99" is invalid on kubectl v1.5.1

### ISSUE THREAD

**Issue by rafaelrpinto** [ContainerSolutions/registry-tooling#5]
`$ cat /etc/*-release file.`
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
[..]

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

`$ ./reg-tool.sh install-k8s-reg`

Installs a Docker registry in your Kubernetes cluster and configures it
[...]
Do you want to continue? (y/n) Y

Tidying up any old registry jobs

Creating new registry certificate
job "create-certs" created

Waiting for job to complete.............................
Copying certs to nodes
**The Job "copy-certs-172.17.4.99" is invalid: spec.template.spec.containers[0].name: Invalid value: "copy-certs-172.17.4.99": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or '123-abc')**

**Comment by rafaelrpinto** [comment]
I was using a coreos vagrant VM with a single-node cluster. Moved to minikube and worked fine.

**Comment by amouat** [comment]
Annoying. Should be an easy fix though. Thanks!

**Comment by amouat** [comment]
I've changed the job names to use `metadata.uid` rather than `metadata.name` as a suffix, which should solve this problem. I'm closing for the moment, let me know if you still have problems.
